### ISSUE TITLE
Ticket Vendor crashes when I click the "Ticket" button

### ISSUE THREAD

**Issue by JadianRadiator** [KyleLin921021/EkiMod#3] opened 2020-07-19 11:15 UTC
Ticket Vendor crashes when I click the "Ticket" button.
[crash-reports\crash-2020-07-19_06.05.32-client.txt](https://hastebin.com/kogenazilu.hs)
[logs\latest.log](https://hastebin.com/osubazizaz.log)
[logs\debug.log](https://hastebin.com/varudaruje.log)
[logs\oxygen\common\oxygen.log](https://hastebin.com/mucebuxigo.log)
[Curse pack profile export of the pack setup so I can be lazy about the mod list](https://www.dropbox.com/s/s6vuifjg0qc4cxz/Economica-1.0.0.zip?dl=0)

**Comment by ChAoSUnItY** [comment] 2020-07-19 11:47
It seems like eki mod's capability to grand economy is outdated , your grand economy is 2.0.0, and eki mod supports older versions.
Thanks for the report!
I'll release 1.2.4 version ASAP, please hold :)

**Comment by ChAoSUnItY** [comment] 2020-07-20 07:24
The issue is now fixed in 1.2.4 , [Eki Mod 1.2.4](https://www.curseforge.com/minecraft/mc-mods/eki-mod/files/3009634)

**Closed as completed by ChAoSUnItY** 2020-07-20 07:24 UTC
